baseURL = "https://arthurolg.com/"
DefaultContentLanguage = "es"
languageCode = "es"
title = "Arturo López"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClassic = true
pygmentOptions = "linenos=inline"
googleAnalytics = "UA-42486999-1"
disqusShortname = "lgzarturo"
enableGitInfo = true

[Params]
    homeTitle = "Desarrollo web"
    subtitle = "Notas sobre diseño y programación de software"
    mainSections = ["post","posts"]
    logo = "assets/images/avatar.png"
    favicon = "assets/images/favicon.svg"
    dateFormat = "2006-01-02"
    commit = true
    rss = true
    comments = true
    readingTime = true
    wordCount = true
    useHLJS = true
    socialShare = true
    delayDisqus = true
    showRelatedPosts = true
    gcse = "012631372760530287590:WMX-216129434"

[Author]
    name = "Arturo López"
    website = "webdeveloperhints.com"
    email = "arthurolg@gmail.com"
    github = "lgzarturo"
    twitter = "lgzarturo"
    linkedin = "lgzarturo"
    instagram = "lgzarturo"
    youtube = "channel/UCyKhlRUjrZetRu84q9SzUwA"
    paypal = "arthurolg"
    telegram = "lgzarturo"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Sobre mí"
    url = "about/"
    weight = 2

[[menu.main]]
  name = "Perfil"
  url = "profile/"
  weight = 2

[[menu.main]]
    name = "Etiquetas"
    url = "tags"
    weight = 2

[params.footer]
    copyright = "Arturo López - Creative Commons Atribución 4.0 Internacional"
